[package]
name = "prevy"
version = "0.1.0"
authors = ["Fabien Dubosson <fabien.dubosson@gmail.com>"]

[dependencies]
ansi_term = "0.7"
atty = "0.1"
clap = "2"
threadpool = "1"
xdg-basedir = "1"
yaml-rust = "0.3"
